# Generated by Django 5.2.3 on 2025-06-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipo',
            old_name='logo',
            new_name='company_logo',
        ),
    ]
